# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dfd2d8d6a8ac0348cf069ad568e70c855b376710f05dc9daf9b89a055e49636b500436853b2827302d93e46b5908472cf94c81f7907992dcb2fef050f379cd4

test:
  secret_key_base: 09f687a02cb3eed6e1f257d7a63e862d5c97613c970486877f9c811ca868e105536ff4813394e9a8a681b4b8db809814608a2003ab340582df1a0b53b6ced85a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
